version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5532:5432"
    environment:
      POSTGRES_USER: 3KmxzdsJNNNuse8X4w9G
      POSTGRES_PASSWORD: wma9uHKWbRbwyjtJ39sx
      POSTGRES_DB: outline
    user: "postgres:postgres"
  s3:
    image: lphoward/fake-s3
    ports:
      - "127.0.0.1:4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
